version: "3.7"
services:
    lookbook_api:
        build: .
        ports:
            - 8000:8000
        environment: 
            - MONGO_URL=mongodb://mongo:27017
        depends_on: 
            - mongo

    mongo:
        image: mongo:4.2.5
        container_name: "mongodb"
        volumes:
            - ./mongo_volume:/data/db
        ports:
            - 27017:27017
        
    
    
