version: "3.7"
services:
    lookbook_client:
        build: ./client
        ports:
            - 3000:3000
        stdin_open: true
        depends_on: 
            - lookbook_api
            
    lookbook_api:
        build: ./server
        ports:
            - 8000:8000
        environment: 
            - MONGO_URL=mongodb://mongo:27017
        depends_on: 
            - mongo

    mongo:
        image: mongo:4.2.5
        container_name: "mongodb"
        volumes:
            - ./Desktop/mongo_volume:/data/db
        ports:
            - 27017:27017
        
    
    
