version: "3.7"
services:
    lookbook_client:
        build: ./client
        ports:
            - 3000:3000
        stdin_open: true
        depends_on: 
            - lookbook_api
        environment:
            - REACT_APP_USER_LOGIN=http://lookbook_api:8000/api/user/login
            - REACT_APP_USER_REGISTER=http://lookbook_api:8000/api/user/register
            - REACT_APP_RECIPE_ADD=http://lookbook_api:8000/api/recipe/add
            - REACT_APP_RECIPE_GET_BASE=http://lookbook_api:8000/api/recipe
            - REACT_APP_RECIPE_UPDATE=http://lookbook_api:8000/api/recipe/update
            - REACT_APP_RECIPE_ALL=http://lookbook_api:8000/api/recipe/all
            - REACT_APP_RECIPE_USER_BASE=http://lookbook_api:8000/api/recipe/user
            - REACT_APP_RECIPE_DELETE_BASE=http://lookbook_api:8000/api/recipe

    lookbook_api:
        build: ./server
        ports:
            - 8000:8000
        environment: 
            - MONGO_URL=mongodb://mongo:27017
        depends_on: 
            - mongo

    mongo:
        image: mongo:4.2.5
        container_name: "mongodb"
        volumes:
            - ./Desktop/mongo_volume:/data/db
        ports:
            - 27017:27017
        
    
    
