version: "3.7"
services:
    client:
        build: ./client
        ports:
            - 3000:3000
        stdin_open: true
        environment:
            - REACT_APP_USER_LOGIN=http://server:8000/api/user/login
            - REACT_APP_USER_REGISTER=http://server:8000/api/user/register
            - REACT_APP_RECIPE_ADD=http://server:8000/api/recipe/add
            - REACT_APP_RECIPE_GET_BASE=http://server:8000/api/recipe
            - REACT_APP_RECIPE_UPDATE=http://server:8000/api/recipe/update
            - REACT_APP_RECIPE_ALL=http://server:8000/recipe/all
            - REACT_APP_RECIPE_USER_BASE=http://server:8000//api/recipe/user
            - REACT_APP_RECIPE_DELETE_BASE=http://server:8000/api/recipe
        depends_on: 
            - server

    server:
        build: ./server
        ports:
            - 8000:8000
        environment: 
            - MONGO_URL=mongodb://mongo:27017
        depends_on: 
            - mongo

    mongo:
        image: mongo:4.2.5
        container_name: "mongodb"
        volumes:
            - ./Desktop/mongo_volume:/data/db
        ports:
            - 27017:27017
        
    
    
